version: '2'
services:
  database:
    image: mysql:5.7
    environment:
      TZ: Asia/Tokyo
      MYSQL_DATABASE: develop
      MYSQL_USER: develop
      MYSQL_PASSWORD: develop
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3307:3306"
