version: '2'
services:
  database:
    image: mysql:5.7
    environment:
      TZ: Asia/Tokyo
      MYSQL_DATABASE: development
      MYSQL_USER: devel
      MYSQL_PASSWORD: development
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
