version: '2'

services:
  db:
    build:
      context: ./docker
      dockerfile: Dockerfile.postgres
  php-fpm:
    build:
      context: ./docker
      dockerfile: Dockerfile.php-fpm
    volumes:
      - ./public/:/var/www/html
    links:
      - db
  web:
    ports:
      - "80:80"
    build:
      context: ./docker
      dockerfile: Dockerfile.nginx
    volumes:
      - ./public/:/var/www/html
    links:
      - db
